# Generated by Django 6.0.5 on 2026-05-12 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Brief description shown on the homepage card.')),
                ('icon', models.CharField(default='📘', help_text='Emoji or icon class for the module card.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published modules are visible to learners.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RevisionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(help_text='Condensed summary of the module concepts.')),
                ('key_points', models.TextField(blank=True, help_text='Bullet-point key takeaways (one per line).')),
                ('mindmap_data', models.TextField(blank=True, help_text='JSON or text structure for mind-map visualization.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_notes', to='core.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('introduction', models.TextField(blank=True, help_text='Opening paragraph introducing the topic.')),
                ('content_html', models.TextField(blank=True, help_text='Main explanation content (supports HTML/Markdown).')),
                ('code_examples', models.TextField(blank=True, help_text='Code snippets demonstrating the concept.')),
                ('logic_explanation', models.TextField(blank=True, help_text='Step-by-step logic breakdown.')),
                ('common_mistakes', models.TextField(blank=True, help_text='Frequent mistakes beginners make.')),
                ('beginner_notes', models.TextField(blank=True, help_text='Friendly tips and encouragement for beginners.')),
                ('visual_explanation', models.TextField(blank=True, help_text='Diagrams, ASCII art, or image URLs.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.module')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Problem statement in clear language.')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('category', models.CharField(choices=[('guided', 'Guided Problem'), ('practice', 'Practice'), ('challenge', 'Challenge')], default='guided', max_length=20)),
                ('hints', models.TextField(blank=True, help_text='Hints to guide the learner.')),
                ('solution_code', models.TextField(blank=True, help_text='Complete solution code.')),
                ('solution_explanation', models.TextField(blank=True, help_text='Step-by-step explanation of the solution.')),
                ('is_assignment', models.BooleanField(default=False, help_text='Mark as an assignment (vs. guided problem).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.topic')),
            ],
            options={
                'ordering': ['order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('explanation', models.TextField(help_text='Clear, beginner-friendly explanation.')),
                ('code_snippet', models.TextField(blank=True, help_text='Optional code example for this concept.')),
                ('language', models.CharField(default='python', help_text='Programming language for syntax highlighting.', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
