# Generated by Django 6.0.5 on 2026-05-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description shown on the homepage card.')),
                ('icon', models.CharField(default='📘', help_text='Emoji or icon class.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='concept',
            name='code_snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='language',
            field=models.CharField(default='python', max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hints',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='revisionnote',
            name='key_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='revisionnote',
            name='mindmap_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='revisionnote',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='beginner_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='code_examples',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='common_mistakes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='logic_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='visual_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('code', 'Code'), ('callout', 'Callout'), ('assignment', 'Assignment'), ('revision', 'Revision'), ('divider', 'Divider')], max_length=20)),
                ('content', models.TextField(blank=True, help_text='Block content — text, markdown, or code.')),
                ('language', models.CharField(blank=True, default='', help_text="Language for code blocks (e.g. 'c', 'python').", max_length=30)),
                ('meta_json', models.JSONField(blank=True, default=dict, help_text='Extra metadata: {level, style, difficulty, hints, keyPoints}')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Parent series. Null for legacy modules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.series'),
        ),
    ]
